use crate::{BlackboxConditionalFieldDefinition, BlackboxMainFieldDefinition, BlackboxSimpleFieldDefinition};
use crate::{FlightLogField, FlightLogFieldCondition, FlightLogFieldEncoding, FlightLogFieldPredictor};

pub const SLOW_FIELD_COUNT: usize = 5;

pub static BLACKBOX_SLOW_FIELDS: [BlackboxSimpleFieldDefinition; SLOW_FIELD_COUNT] = [
    BlackboxSimpleFieldDefinition {
        name: "flight_mode_flags",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
    },
    BlackboxSimpleFieldDefinition {
        name: "state_flags",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
    },
    BlackboxSimpleFieldDefinition {
        name: "failsafe_phase",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::TAG2_3S32,
    },
    BlackboxSimpleFieldDefinition {
        name: "rx_signal_received",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::TAG2_3S32,
    },
    BlackboxSimpleFieldDefinition {
        name: "rx_flight_channel_is_valid",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::TAG2_3S32,
    },
];

// GPS home frame
pub const GPS_H_FIELD_COUNT: usize = 3;
pub static BLACKBOX_GPS_H_FIELDS: [BlackboxSimpleFieldDefinition; GPS_H_FIELD_COUNT] = [
    BlackboxSimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
    },
    BlackboxSimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
    },
    BlackboxSimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
    },
];

// GPS position/velocity frame
pub const GPS_G_FIELD_COUNT: usize = 10;
pub static BLACKBOX_GPS_G_FIELDS: [BlackboxConditionalFieldDefinition; GPS_G_FIELD_COUNT] = [
    BlackboxConditionalFieldDefinition {
        name: "time",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::LAST_MAIN_FRAME_TIME,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
        condition: FlightLogFieldCondition::NOT_LOGGING_EVERY_FRAME,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_numSat",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_coord",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::HOME_COORD,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_coord",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::HOME_COORD,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_altitude",
        field_name_index: -1,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_speed",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_ground_course",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::UNSIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        predict: FlightLogFieldPredictor::ZERO,
        encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
];

pub static BLACKBOX_MAIN_FIELDS: &[BlackboxMainFieldDefinition] = &[
    // loopIteration doesn't appear in P frames since it always increments
    BlackboxMainFieldDefinition {
        name: "loopIteration",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::UNSIGNED_VB,
        p_predict: FlightLogFieldPredictor::INC,
        p_encode: FlightLogFieldEncoding::ZERO,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    // Time advances pretty steadily so the P-frame prediction is a straight line
    BlackboxMainFieldDefinition {
        name: "time",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::UNSIGNED_VB,
        p_predict: FlightLogFieldPredictor::STRAIGHT_LINE,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::ALWAYS,
    },
    BlackboxMainFieldDefinition {
        name: "axisP",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID,
    },
    BlackboxMainFieldDefinition {
        name: "axisP",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID,
    },
    BlackboxMainFieldDefinition {
        name: "axisP",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID,
    },
    // I terms get special packed encoding in P frames:
    BlackboxMainFieldDefinition {
        name: "axisI",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG2_3S32,
        condition: FlightLogFieldCondition::PID,
    },
    BlackboxMainFieldDefinition {
        name: "axisI",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG2_3S32,
        condition: FlightLogFieldCondition::PID,
    },
    BlackboxMainFieldDefinition {
        name: "axisI",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG2_3S32,
        condition: FlightLogFieldCondition::PID,
    },
    BlackboxMainFieldDefinition {
        name: "axisD",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_D_ROLL,
    },
    BlackboxMainFieldDefinition {
        name: "axisD",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_D_PITCH,
    },
    BlackboxMainFieldDefinition {
        name: "axisD",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_D_YAW,
    },
    // PID K terms use F (feedforward) suffix, for Betaflight compatibility.
    BlackboxMainFieldDefinition {
        name: "axisF",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_K,
    },
    BlackboxMainFieldDefinition {
        name: "axisF",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_K,
    },
    BlackboxMainFieldDefinition {
        name: "axisF",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_K,
    },
    BlackboxMainFieldDefinition {
        name: "axisS",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_S_ROLL,
    },
    BlackboxMainFieldDefinition {
        name: "axisS",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_S_PITCH,
    },
    BlackboxMainFieldDefinition {
        name: "axisS",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::SIGNED_VB,
        condition: FlightLogFieldCondition::PID_S_YAW,
    },
    // rc_commands are encoded together as a group in P-frames:
    BlackboxMainFieldDefinition {
        name: "rc_command",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::RC_COMMANDS,
    },
    BlackboxMainFieldDefinition {
        name: "rc_command",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::RC_COMMANDS,
    },
    BlackboxMainFieldDefinition {
        name: "rc_command",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::RC_COMMANDS,
    },
    BlackboxMainFieldDefinition {
        name: "rc_command",
        field_name_index: 3,
        is_signed: FlightLogField::UNSIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::UNSIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::RC_COMMANDS,
    },
    // setpoint
    BlackboxMainFieldDefinition {
        name: "setpoint",
        field_name_index: 0,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::SETPOINT,
    },
    BlackboxMainFieldDefinition {
        name: "setpoint",
        field_name_index: 1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::SETPOINT,
    },
    BlackboxMainFieldDefinition {
        name: "setpoint",
        field_name_index: 2,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::SETPOINT,
    },
    BlackboxMainFieldDefinition {
        name: "setpoint",
        field_name_index: 3,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_4S16,
        condition: FlightLogFieldCondition::SETPOINT,
    },
    BlackboxMainFieldDefinition {
        name: "vbat_latest",
        field_name_index: -1,
        is_signed: FlightLogField::UNSIGNED,
        i_predict: FlightLogFieldPredictor::VBATREF,
        i_encode: FlightLogFieldEncoding::NEG_14BIT,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_8SVB,
        condition: FlightLogFieldCondition::BATTERY_VOLTAGE,
    },
    BlackboxMainFieldDefinition {
        name: "amperage_latest",
        field_name_index: -1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_8SVB,
        condition: FlightLogFieldCondition::BATTERY_CURRENT,
    },
    #[cfg(feature = "barometer")]
    BlackboxMainFieldDefinition {
        name: "baro_altitude",
        field_name_index: -1,
        is_signed: FlightLogField::SIGNED,
        i_predict: FlightLogFieldPredictor::ZERO,
        i_encode: FlightLogFieldEncoding::SIGNED_VB,
        p_predict: FlightLogFieldPredictor::PREVIOUS,
        p_encode: FlightLogFieldEncoding::TAG8_8SVB,
        condition: FlightLogFieldCondition::BAROMETER,
    },
];
