use crate::{ConditionalFieldDefinition, MainFieldDefinition, SimpleFieldDefinition};
use crate::{FieldSign, FieldCondition, FieldEncoding, FieldPredictor};

pub const SLOW_FIELD_COUNT: usize = 5;

pub static BLACKBOX_SLOW_FIELDS: [SimpleFieldDefinition; SLOW_FIELD_COUNT] = [
    SimpleFieldDefinition {
        name: "flight_mode_flags",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::UNSIGNED_VB,
    },
    SimpleFieldDefinition {
        name: "state_flags",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::UNSIGNED_VB,
    },
    SimpleFieldDefinition {
        name: "failsafe_phase",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::TAG2_3S32,
    },
    SimpleFieldDefinition {
        name: "rx_signal_received",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::TAG2_3S32,
    },
    SimpleFieldDefinition {
        name: "rx_flight_channel_is_valid",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::TAG2_3S32,
    },
];

// GPS home frame
pub const GPS_H_FIELD_COUNT: usize = 3;
pub static BLACKBOX_GPS_H_FIELDS: [SimpleFieldDefinition; GPS_H_FIELD_COUNT] = [
    SimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
    },
    SimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
    },
    SimpleFieldDefinition {
        name: "GPS_home",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
    },
];

// GPS position/velocity frame
pub const GPS_G_FIELD_COUNT: usize = 10;
pub static BLACKBOX_GPS_G_FIELDS: [ConditionalFieldDefinition; GPS_G_FIELD_COUNT] = [
    ConditionalFieldDefinition {
        name: "time",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::LAST_MAIN_FRAME_TIME,
        encode: FieldEncoding::UNSIGNED_VB,
        condition: FieldCondition::NOT_LOGGING_EVERY_FRAME,
    },
    ConditionalFieldDefinition {
        name: "GPS_numSat",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::UNSIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_coord",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::HOME_COORD,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_coord",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::HOME_COORD,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_altitude",
        field_name_index: -1,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_speed",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::UNSIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_ground_course",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::UNSIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    ConditionalFieldDefinition {
        name: "GPS_velned",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        predict: FieldPredictor::ZERO,
        encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
];

pub static BLACKBOX_MAIN_FIELDS: &[MainFieldDefinition] = &[
    // loopIteration doesn't appear in P frames since it always increments
    MainFieldDefinition {
        name: "loopIteration",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::UNSIGNED_VB,
        p_predict: FieldPredictor::INC,
        p_encode: FieldEncoding::ZERO,
        condition: FieldCondition::ALWAYS,
    },
    // Time advances pretty steadily so the P-frame prediction is a straight line
    MainFieldDefinition {
        name: "time",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::UNSIGNED_VB,
        p_predict: FieldPredictor::STRAIGHT_LINE,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ALWAYS,
    },
    MainFieldDefinition {
        name: "axisP",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID,
    },
    MainFieldDefinition {
        name: "axisP",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID,
    },
    MainFieldDefinition {
        name: "axisP",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID,
    },
    // I terms get special packed encoding in P frames:
    MainFieldDefinition {
        name: "axisI",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG2_3S32,
        condition: FieldCondition::PID,
    },
    MainFieldDefinition {
        name: "axisI",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG2_3S32,
        condition: FieldCondition::PID,
    },
    MainFieldDefinition {
        name: "axisI",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG2_3S32,
        condition: FieldCondition::PID,
    },
    MainFieldDefinition {
        name: "axisD",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_D_ROLL,
    },
    MainFieldDefinition {
        name: "axisD",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_D_PITCH,
    },
    MainFieldDefinition {
        name: "axisD",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_D_YAW,
    },
    // PID K terms use F (feedforward) suffix, for Betaflight compatibility.
    MainFieldDefinition {
        name: "axisF",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_K,
    },
    MainFieldDefinition {
        name: "axisF",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_K,
    },
    MainFieldDefinition {
        name: "axisF",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_K,
    },
    MainFieldDefinition {
        name: "axisS",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_S_ROLL,
    },
    MainFieldDefinition {
        name: "axisS",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_S_PITCH,
    },
    MainFieldDefinition {
        name: "axisS",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::PID_S_YAW,
    },
    // rc_commands are encoded together as a group in P-frames:
    MainFieldDefinition {
        name: "rc_command",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::RC_COMMANDS,
    },
    MainFieldDefinition {
        name: "rc_command",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::RC_COMMANDS,
    },
    MainFieldDefinition {
        name: "rc_command",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::RC_COMMANDS,
    },
    MainFieldDefinition {
        name: "rc_command",
        field_name_index: 3,
        is_signed: FieldSign::UNSIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::UNSIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::RC_COMMANDS,
    },
    // setpoint
    MainFieldDefinition {
        name: "setpoint",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::SETPOINT,
    },
    MainFieldDefinition {
        name: "setpoint",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::SETPOINT,
    },
    MainFieldDefinition {
        name: "setpoint",
        field_name_index: 2,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::SETPOINT,
    },
    MainFieldDefinition {
        name: "setpoint",
        field_name_index: 3,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_4S16,
        condition: FieldCondition::SETPOINT,
    },
    MainFieldDefinition {
        name: "vbat_latest",
        field_name_index: -1,
        is_signed: FieldSign::UNSIGNED,
        i_predict: FieldPredictor::VBATREF,
        i_encode: FieldEncoding::NEG_14BIT,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_8SVB,
        condition: FieldCondition::BATTERY_VOLTAGE,
    },
    MainFieldDefinition {
        name: "amperage_latest",
        field_name_index: -1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_8SVB,
        condition: FieldCondition::BATTERY_CURRENT,
    },
    #[cfg(feature = "barometer")]
    MainFieldDefinition {
        name: "baro_altitude",
        field_name_index: -1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::PREVIOUS,
        p_encode: FieldEncoding::TAG8_8SVB,
        condition: FieldCondition::BAROMETER,
    },
    MainFieldDefinition {
        name: "gyro_adc",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::GYRO,
    },
    MainFieldDefinition {
        name: "gyro_adc",
        field_name_index: 1,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::GYRO,
    },
    MainFieldDefinition {
        name: "gyroUnfilt",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::GYRO_UNFILTERED,
    },
    MainFieldDefinition {
        name: "accSmooth",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ACC,
    },
    MainFieldDefinition {
        name: "imuQuaternion",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::ATTITUDE,
    },
    MainFieldDefinition {
        name: "debug",
        field_name_index: 0,
        is_signed: FieldSign::SIGNED,
        i_predict: FieldPredictor::ZERO,
        i_encode: FieldEncoding::SIGNED_VB,
        p_predict: FieldPredictor::AVERAGE_2,
        p_encode: FieldEncoding::SIGNED_VB,
        condition: FieldCondition::DEBUG,
    },
];
